# Generated by Django 4.0.2 on 2022-08-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='profileImg',
        ),
        migrations.AddField(
            model_name='teammember',
            name='img_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
