# Generated by Django 4.0.2 on 2022-08-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_competitionimage_img_competitionimage_img_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='poster_img',
        ),
        migrations.RemoveField(
            model_name='event',
            name='poster_img',
        ),
        migrations.RemoveField(
            model_name='eventimage',
            name='img',
        ),
        migrations.AddField(
            model_name='competition',
            name='poster_img_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='poster_img_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='eventimage',
            name='img_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
